# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.2
_src_path: gh:algorand-devrel/starter-algokit-beaker-template
algod_port: '4001'
algod_server: http://localhost
algod_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
author_email: null
author_name: null
ide_vscode: true
indexer_port: '8980'
indexer_server: http://localhost
indexer_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
project_name: global_storage_dao
python_linter: ruff
use_python_black: true
use_python_mypy: true
use_python_pip_audit: true
use_python_pytest: true

