tasks:
  - name: Install Python
    init: pyenv install 3.10.7 && pyenv global 3.10.7
  - name: Install and initialize Sandbox
    init: git clone https://github.com/algorand/sandbox && /workspace/bootcamp/sandbox/sandbox up dev -v && /workspace/bootcamp/sandbox/sandbox down 
  - name: Start Sandbox
    command: /workspace/bootcamp/sandbox/sandbox reset
vscode:
  extensions:
    - ms-python.python
