tasks:
  - name: Install Python
    init: pyenv install 3.10.7 && pyenv global 3.10.7
  - name: Install and Start Sandbox
    init: git clone https://github.com/algorand/sandbox && /workspace/bootcamp/sandbox/sandbox up dev -v
  - name: Get Status
    command: python --version && docker --version && /workspace/bootcamp/sandbox/sandbox status
vscode:
  extensions:
    - ms-python.python
