image:
  file: .gitpod.Dockerfile
tasks:
  - name: start localnet
    command: >
      gp sync-await algokit-upgrade && 
      algokit localnet start && 
      exit
  - name: upgrade algokit
    command: >
      pipx upgrade algokit && 
      gp sync-done algokit-upgrade  &&
      exit
vscode:
  extensions:
    - ms-python.python
ports:
  - name: algod
    port: 4001
    visibility: public
    onOpen: ignore
  - name: indexer
    port: 8980
    visibility: public
    onOpen: ignore
  - name: postgres
    port: 5432
    onOpen: ignore
  - name: kmd
    port: 4002
    visibility: public
    onOpen: ignore
  - name: debug port
    port: 9392
    onOpen: ignore
    visibility: public
  - name: webpack
    port: 8080
    visibility: public
    onOpen: ignore
