# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.7.1-12-g4301592
_src_path: https://github.com/algorandfoundation/algokit-react-frontend-template
algod_port: 4001
algod_server: http://localhost
algod_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
author_email: your@email.tld
author_name: Your-Name
cloud_provider: netlify
ide_vscode: true
indexer_port: 8980
indexer_server: http://localhost
indexer_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
project_name: frontend
use_daisy_ui: true
use_eslint_prettier: true
use_github_actions: false
use_jest: true
use_playwright: true
use_tailwind: true

