# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.0
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: your@email.tld
author_name: Your-Name
cloud_provider: none
contract_name: dao
ide_vscode: true
preset_name: starter
project_name: dao
python_linter: none
use_dispenser: false
use_github_actions: true
use_python_black: true
use_python_mypy: false
use_python_pip_audit: true
use_python_pytest: true

