# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.0-38-gd30492e
_src_path: https://github.com/algorandfoundation/algokit-beaker-default-template
algod_port: 4001
algod_server: http://localhost
algod_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
author_email: your@email.tld
author_name: Your-Name
contract_name: auction
deployment_language: typescript
ide_vscode: true
indexer_port: 8980
indexer_server: http://localhost
indexer_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
preset_name: starter
project_name: backend
python_linter: none
use_dispenser: false
use_github_actions: false
use_pre_commit: false
use_python_black: true
use_python_mypy: false
use_python_pip_audit: true
use_python_pytest: true

