# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.2.1-18-g980b749
_src_path: https://github.com/algorandfoundation/algokit-fullstack-template
author_email: your@email.tld
author_name: Your-Name
cloud_provider: none
contract_name: auction
ide_vscode: true
preset_name: starter
project_name: auction
python_linter: none
use_dispenser: false
use_github_actions: true
use_python_black: true
use_python_mypy: false
use_python_pip_audit: true
use_python_pytest: true

