name: Pull Request validation

on: [pull_request]

jobs:
    smart-contracts-ci:
        name: Smart Contracts CI
        uses: ./.github/workflows/smart-contracts-ci.yaml

    frontend-ci:
        name: Frontend CI
        uses: ./.github/workflows/frontend-ci.yaml
